apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nutritious-lizard-python 
  janus-idp.io/tekton: nutritious-lizard-python
  backstage.io/kubernetes-id: nutritious-lizard-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nutritious-lizard-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  