apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nutritious-lizard-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nutritious-lizard-python 
  name: nutritious-lizard-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nutritious-lizard-python 
